Id generator
VPeron/cc_detector pull request #10
Opened 2021-11-13 17:08 UTC by Jo-llama

Functions for players ID created and implemented in data.py

2021-11-16 13:19 UTC, VPeron commented
can you add a brief comment with the files that have been modified please?

2021-11-16 13:24 UTC, VPeron approved these changes

2021-11-16 18:18 UTC, Manu2212 requested changes
- remove Zone.Identifiers from push (add it to .gitignore)
- add pgn_to_3dfs_Manuel.ipynb back to push

2021-11-18 18:34 UTC, Manu2212 approved these changes

2021-11-18 18:34 UTC, merged